# -*- coding: utf-8 -*-
{
    'name': 'Argos App',
    'summary': '',
    'category': 'Application',
    'version': '1.0',
    'sequence': -100,
    'author': 'Omar OUHARI',
    'license': 'AGPL-3',
    'website': 'https://arkeup.com',
    'description': '',
    'depends': [
        'argos_calendar',
        'argos_impex',
        'arkeup_keyyo',
        'argos_stock',
        'argos_website',
        'argos_purchase',
        'argos_hr',
        'argos_sale_subscription',
        'argos_i18n',
        'argos_sale_project',
        'argos_planning_sale',
        'ks_dashboard_ninja',
    ],
    'data': [],
    'application': True,
    'installable': True,
    'auto_install': False,
}
