# -*- coding: utf-8 -*-
{
    'name': 'Argos App',
    'summary': '',
    'category': 'Application',
    'version': '1.0',
    'sequence': -100,
    'author': 'Omar OUHARI',
    'license': 'AGPL-3',
    'website': 'https://arkeup.com',
    'description': '',
    'depends': [
        'argos_calendar',
        'argos_impex',
        'arkeup_keyyo',
        'argos_stock',
        'argos_planning',
        'argos_website',
        'argos_sale',
        'argos_contact',
        'argos_operating_unit',
    ],
    'data': [],
    'application': True,
    'installable': True,
    'auto_install': False,
}
